# Generated by Django 4.0.1 on 2022-01-19 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_restaurant_user'),
        ('employee', '0002_remove_employee_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.restaurant'),
        ),
    ]
