# Generated by Django 4.0.1 on 2022-01-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='restuarant',
            new_name='restaurant',
        ),
    ]
