# Generated by Django 4.0.1 on 2022-01-20 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_restaurant_user'),
        ('vote', '0002_rename_restuarant_vote_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='restaurant',
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vote.candidate'),
            preserve_default=False,
        ),
    ]
