# Generated by Django 4.0.1 on 2022-01-20 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_remove_vote_restaurant_candidate_vote_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='vote.candidate'),
        ),
    ]
