# Generated by Django 4.0.1 on 2022-01-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_vote_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='A', max_length=250),
            preserve_default=False,
        ),
    ]
