# Generated by Django 4.0.1 on 2022-01-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
