# Generated by Django 4.0.1 on 2022-01-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
