# Generated by Django 4.0.1 on 2022-01-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_item_restaurant_item_user_menu_restaurant_menu_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
